apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rds-${{ values.name }}
  title: ${{ values.name }} [${{ values.environment }}] (PostgreSQL)
  description: ${{ values.description | dump }}
  annotations:
    aws.amazon.com/cost-insights-tags: resource=${{ values.name }},resource-type=rds-postgres,environment=${{ values.environment }}
  tags:
    - aws
    - rds
  links:
    - url: https://ap-south-1.console.aws.amazon.com/rds/home?region=ap-south-1#database:id=devops94-idp-${{ values.environment }}-res-${{ values.name }}
      title: RDS console
      icon: cloud
    - url: https://github.com/0019-KDU/platform-resources/tree/main/resources/${{ values.type }}/${{ values.name }}
      title: Terraform definition
      icon: github
spec:
  type: postgres-database
  owner: ${{ values.owner }}
  system: idp-demo
{%- if values.component %}
  dependencyOf:
    - ${{ values.component }}
{%- endif %}
