apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ec2-${{ values.name }}
  title: ${{ values.name }} [${{ values.environment }}] (EC2 instance)
  description: ${{ values.description | dump }}
  annotations:
    aws.amazon.com/cost-insights-tags: resource=${{ values.name }},resource-type=ec2-instance,environment=${{ values.environment }}
  tags:
    - aws
    - ec2
  links:
    - url: https://ap-south-1.console.aws.amazon.com/ec2/home?region=ap-south-1#Instances:tag:Name=devops94-idp-${{ values.environment }}-res-${{ values.name }}
      title: EC2 console
      icon: cloud
    - url: https://github.com/0019-KDU/platform-resources/tree/main/resources/${{ values.type }}/${{ values.name }}
      title: Terraform definition
      icon: github
spec:
  type: virtual-machine
  owner: ${{ values.owner }}
  system: idp-demo
{%- if values.component %}
  dependencyOf:
    - ${{ values.component }}
{%- endif %}
